// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBHuan.TestQRCode
{
    /// <summary>
    /// Bảng lưu thông tin cấu hình
    /// </summary>
    public partial class Config
    {
        /// <summary>
        /// Khóa chính
        /// </summary>
        public Guid Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    }
}