version: '3.4'

services:
  qrcode:
    image: 01686120288/test-qrcode:1.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5005:3000
